<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OnlineService extends Model
{
    public $table = 'online_services';
    public $fillable = [
        'account_id',
        'attendingForum',
        'presentationForum',
        'presentation',
        'programBook',
        'first_name',
        'last_name',
        'gender',
        'birthday',
        'title',
        'position',
        'institution',
        'home_phone',
        'mobile_phone',
        'nationality',
        'passport_number',
        'issue_date',
        'expire_date',
        'address1',
        'floor',
        'address2',
        'city',
        'state',
        'country',
        'postal_code',
        'date_of_arrival',
        'date_of_departure',
        'other_date_of_arrival',
        'other_date_of_departure',
        'other_time_of_arrival',
        'other_time_of_departure',
        'other_flight_number_arrival',
        'other_flight_number_departure',
        'other_name_airport_arrival',
        'other_name_airport_departure',
        'room',
        'indicate',
        'obtain_visa',
        'where_visa',
        'join_hanoi',
        'accompanying_other',
        'accom_first_name',
        'accom_last_name',
        'accom_gender',
        'accom_birthday',
        'accom_nationality',
        'accom_passport_number',
        'accom_issue_date',
        'accom_expire_date',
        'accompanying_attend',
        'event_1',
        'event_2',
        'panel_1',
        'panel_2',
        'panel_3',
        'panel_4',
        'panel_5',
        'event_3',
        'accom_obtain_visa',
        'accom_where_visa',
    ];
    public $casts = [
      'room' => 'array',
      'indicate' => 'array',
    ];
}
